version: '3'

services:
  # frontend:
  #   image: curr-conv-fe:1.0
  #   container_name: fe-currency-converter
  #   build: ./client
  #   working_dir: /app/services/client
  #   restart: always
  #   volumes:
  #     - ./client:/app/services/client
  #   networks:
  #       - backend
  #   ports:
  #     - "80:80"

  backend:
    #image: curr-conv-be:1.0
    container_name: be-currency-converter
    build: ./server
    working_dir: /app/services/server
    restart: always
    volumes:
      - ./server:/app/services/server
    networks:
        - backend
    ports:
      - "8000:8000"

  # db:
  #   image: postgres:12-alpine
  #   container_name: db-currency-converter
  #   restart: always
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: app_db
  #   working_dir: /var/lib/postgresql/data
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
  #   networks:
  #       - backend
  #   ports:
  #       - "5600:5432"

# volumes:
#   pgdata:

networks:
  backend:
