# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        #node-version: [10.x, 12.x]
        node-version: [10.x]

    steps:
      - name: Hello world
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: 'Mona the Octocat'
          
          
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1  
      - run: cd ./server
  
      #- name: CD
      #- run: cd ./server
    
    #  uses: actions/setup-node@v1
    #  with:
    #    node-version: ${{ matrix.node-version }}
    #- run: npm ci
    #- run: npm run build --if-present
    #- run: npm test
    #  env:
    #    CI: true
