name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build-be:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      #run:  docker build server . --file Dockerfile --tag my-image-name:$(date +%s)
      run:  |
        docker build ./server -t be-currency-converter:1.0.0
    - name: Login on GitHub Repository
      run:  |    
        docker login docker.pkg.github.com -u MadKerberos -p {{secrets.GITHUB_TOKEN}}
    - name: Tag Image
      run:  |    
        docker tag IMAGE_ID docker.pkg.github.com/madkerberos/currency-converter/IMAGE_NAME:VERSION
